ARG ALPINE_VERSION=3.17
FROM alpine:${ALPINE_VERSION} AS build

WORKDIR /data

COPY /scripts /data/scripts

FROM alpine:${ALPINE_VERSION}
LABEL org.opencontainers.image.source https://github.com/creadigme/github-backup

WORKDIR /data

COPY --from=build /data /data

RUN apk fix && \
    apk --no-cache --update add git git-lfs gpg less openssh patch curl jq && \
    git lfs install

RUN chmod +x /data/scripts/github-backup.sh

ENTRYPOINT ["/data/scripts/github-backup.sh"]
